replicaCount: 1

image:
  repository: sergey1981/react-client
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

backend:
  serviceName: todo-backend-backend
  servicePort: 8080

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: todo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

