replicaCount: 2

image:
  repository: sergey1981/react-client
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

backend:
  serviceName: todo-backend-backend
  servicePort: 8080

resources:
  requests:
    cpu: 400m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi


podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - react-client
        topologyKey: "kubernetes.io/hostname"


ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: todo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
