# mongodb-values.yaml
architecture: standalone
replicaCount: 1
auth:
  enabled: true
  rootPassword: "change-me-root"
  username: "todo"
  password: "change-me-pass"
  database: "test"
primary:
  service:
    type: ClusterIP
volumePermissions:
  enabled: true
persistence:
  enabled: true
  storageClass: "local-path"
  size: 5Gi
resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
# for local development set
# nodeSelector: {}
# tolerations: []
# affinity: {}   # add if you want explicit node anti-affinity for mongo pods
