apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
data:
  DB_URI: "{{ .Values.config.DB_URI }}"
  DB_NAME: "{{ .Values.config.DB_NAME }}"
  DB_COLLECTION_NAME: "{{ .Values.config.DB_COLLECTION_NAME }}"
