apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: go-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DB_URI
              value: {{ .Values.config.DB_URI | quote }}
            - name: DB_NAME
              value: {{ .Values.config.DB_NAME | quote }}
            - name: DB_COLLECTION_NAME
              value: {{ .Values.config.DB_COLLECTION_NAME | quote }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | nindent 12 }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
