replicaCount: 1

image:
  repository: sergey1981/go-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: todo-backend.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] # - secretName: tls-secret, hosts: [todo-backend.local]

config:
  DB_URI: "mongodb://todo:change-me-pass@todo-mongodb.todo-app.svc.cluster.local:27017/test"
  DB_NAME: "test"
  DB_COLLECTION_NAME: "todolist"

podLabels: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
